### ISSUE TITLE
Feature request: format markdown tables

### ISSUE THREAD

**Issue by roblevy** [fannheyward/coc-markdownlint#101]
Is it possible to turn this:

```
|a|b|
|-|-|
|foo|bar|
```
into this:

```
|  a  |  b  |
| --- | --- |
| foo | bar |
```

There seems to be a few ways to do this out in the world, but I can't find one for Coc-vim!

**Comment by fannheyward** [comment]
Try `coc-prettier`, it uses Prettier to do formatting. Tables are support by default.

Tips: `"coc.preferences.formatOnSaveFiletypes": ["markdown"]` will do formatting on saving.
