### ISSUE TITLE
`markdownlint.config` is not allowed error

### ISSUE THREAD

**Issue by lfilho** [fannheyward/coc-markdownlint#124]
Hi there. Thanks for your plugin!

I have the following `coc-settings.json`:

```json
{
  "suggest.noselect": false,
  "coc.preferences.formatOnSaveFiletypes": [
    "css",
    "html",
    "javascript",
    "typescript",
    "typescriptreact",
    "json",
    "javascriptreact",
    "typescript.tsx",
    "graphql"
  ],
  "markdownlint.config": {
    "line_length": false
  }
}
```
And I'm getting this error:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/282756/76708252-a95ede00-66b2-11ea-8ff6-4f73f81b76dc.png">

And indeed it's not working: I open a markdown file and the line_length is still being checked:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/282756/76708279-d3b09b80-66b2-11ea-9064-93d9ce6a2803.png">

Am I missing something?

**Comment by fannheyward** [comment]
Try `:CocCommand workspace.showOutput` and choose `markdownlint` to open log, what's the output?

**Comment by lfilho** [comment]
Hi, thanks for getting back to me. It was a silly mistake of mine: i was using two different vim sessions and in one of them my installation of Coc + Markdownlint was not active yet. Once I restarted vim on that session the above error went away. 😅 

Thanks!
