### ISSUE TITLE
No fix action for bullet lists

### ISSUE THREAD

**Issue by lfilho** [fannheyward/coc-markdownlint#125]
Hello again :)

I got the following lint error:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/282756/76708345-491c6c00-66b3-11ea-80c4-0cc410b1fa95.png">

Shouldn't markdownlint be able to fix that easily?
When I invoke `<Plug>(coc-codeaction)`, the only actions are:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/282756/76708371-76691a00-66b3-11ea-9241-689dda8fb357.png">

Also tried `<Plug>(coc-fix-current)` but it said "`no quick fix action available`"

**Comment by fannheyward** [comment]
The lint and fix are came from [markdownlint](https://github.com/DavidAnson/markdownlint), for your case, markdownlint just provides warning but not fix, `coc-markdownlint` can't do fix action.
