### ISSUE TITLE
Allow configuration of filetypes

### ISSUE THREAD

**Issue by bockel** [fannheyward/coc-markdownlint#137]
Currently, coc-markdownlint is hard coded to only load for markdown filetypes.

This is problematic if you try to load coc-markdownlint in combination with alternate markdown syntax such as [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc). I usually have my markdown files set to `pandoc` or `markdown.pandoc` -- either of which cause this extension to not load.

I would suggest either allowing a wildcard filetypes that include markdown or allowing the user to configure this via a `markdownlint.filetypes` array configuration option in coc-settings.json.

**Comment by fannheyward** [comment]
Add this to your vimrc:

```vim
let g:coc_filetype_map = { 'pandoc': 'markdown' }
```

This will not change your filetype, and coc will treat it as markdown.

**Comment by mtoohey31** [comment]
Hello! The fix posted above worked well for me initially, but I now have a use-case that I don't think this solves: I'd like to use `coc-r-lsp` and `coc-markdownlint` at the same time on an R markdown document, but if I set the filetype map from `rmd` to `markdown`, then `coc-r-lsp` stops working. Is there another work-around for this use case, or a way to use the filetype map to map to more than one filetype at once?
