### ISSUE TITLE
How to correct 

### ISSUE THREAD

**Issue by lanox** [fannheyward/coc-markdownlint#168]
Hi, 

Thanks for the plugin, I was wondering how do I get it to correct? or to bring up the menu?
<img width="823" alt="Screen Shot 2020-05-08 at 5 13 22 pm" src="https://user-images.githubusercontent.com/7599183/81381179-936c1780-914f-11ea-92ea-d66e7a95d12e.png">

I have this in my vimrc
`nmap <leader>ac  <Plug>(coc-codeaction)`

However, when I try to use it I get the below message.

<img width="936" alt="Screen Shot 2020-05-08 at 5 13 14 pm" src="https://user-images.githubusercontent.com/7599183/81381012-45571400-914f-11ea-95b2-0e4691c89dca.png">
also,

 I do see the error being displayed

**Comment by fannheyward** [comment]
Put your cursor on error position and fire codeAction again. For example, line 1 at `#`, line 5 at `*`.

**Comment by lanox** [comment]
Thanks, not sure how I manged to screw that up.

One more question, is it possible to have all warning showing up all the time, what I mean by this if I fix line 1 rest of the W disappear then when I save they come back.
