### ISSUE TITLE
Unintended linting of neovim command results

### ISSUE THREAD

**Issue by ahauser31** [fannheyward/coc-markdownlint#203]
When running features inbuilt in neovim such as the command :checkhealth, the result of the command is opened in a new buffer that is wrongly recognized as a markdown file and consequently linted, which is not great as it's not markdown and every line is highlighted with a linting error, which makes reading the command result difficult.

Is there a way to prevent this? As the command result opens in a unnamed buffer, perhaps linting can be restricted to files with the *.md extension only?

**Comment by fannheyward** [comment]
`:checkhealth` returns result as markdown file, you can check it by `:verbose set filetype`.
