### ISSUE TITLE
Support * for MD004/ul-style

### ISSUE THREAD

**Issue by JasonMFry** [fannheyward/coc-markdownlint#234]
I think `*` is a valid way to start a markdown list. I know there are a lot of different markdowns so maybe some important ones don't support `*`, I don't know. But I prefer to use `*` instead of `-`, but when I do I get `[markdownlint] [W] MD004/ul-style: Unordered list style [Expected: dash; Actual: asterick]`. It would be nice if the config file allowed something like `{ "ul-style": ["*", "-"]}`. Maybe there are really just two valid ones in which case probably don't need a list.

**Comment by fannheyward** [comment]
You can set MD004 in your markdownlint config, for example:

```
  "markdownlint.config": {
    "MD004": { "style": "asterisk" }
  }
```

in your coc-settings.json
