### ISSUE TITLE
Performance Needs Improvement on Windows

### ISSUE THREAD

**Issue by ca-mantis-shrimp** [fannheyward/coc-markdownlint#262]
Hi, 

I love using COC, specifically for Rust code, as well as my Markdown notes. 

However, Coc Markdown's performance on Windows 10 will bring my vim/nvim to a crawl when editing. Especially as I type into a nested header, writing a character can sometimes take upwards of 3 seconds. 

This came after extensive testing of plugin performance and removing all other plugins besides coc. 

No configuration for coc-Markdown, just base implementation installed from the marketplace.

**Comment by fannheyward** [comment]
Please upgrade to latest coc-markdownlint, v1.8.0, and try again. You can also disable lint on change by set `markdownlint.onChange` to false in your coc-settings.json.

**Comment by ca-mantis-shrimp** [comment]
The update did help a little bit. But the option you suggested is the thing that made the plugin usable on my underpowered machine. Thanks for all your demanding work! I almost can't write Markdown these days without your plugin, I appreciate all the value your plugin brings to my workflow.
