### ISSUE TITLE
Bug: Doesn't work when a session is loaded

### ISSUE THREAD

**Issue by Zeioth** [fannheyward/coc-markdownlint#283]
### When a session is loaded like:
```
vim -S my-session.vim
```
In order to make `coc-markdown work`, I have to close the .md buffer and opening it again manually.

**Comment by Zeioth** [comment]
Note that this problem doesn't happen with other linters like coc-python. It seems to be a problem in the conditions that trigger the initialization of coc-markdown.

**Comment by fannheyward** [comment]
Can't reproduce this issue.

**Comment by Zeioth** [comment]
Could you please try to reproduce with [coc's master branch](https://github.com/neoclide/coc.nvim)?

**Comment by Zeioth** [comment]
I confirm this was an issue on my end, due to an incorrect load order in my vimrcs. If someone else experience this issue, please check your vimrcs and file formats. (In my case worked when opening files with vim-ranger but not by open files normally, this was due to ranger opening the file as markdown, while my vimrc opening it as markdown.pandoc. After fixing the issue both formats open correctly).
