### ISSUE TITLE
Receiving TypeError on startup

### ISSUE THREAD

**Issue by weierophinney** [fannheyward/coc-markdownlint#336]
I'm receiving the following error on startup:

```text
[coc.nvim] Error on load extension coc-markdownlint from {path to}/coc/extensions/node_modules/coc-markdownlint/lib/index.js: TypeError: Cannot read property 'createOutputChannel' of undefined
```

I am using:

| Tool | Version |
| ---- | ------- |
| Vim | 8.2 |
| Node | 15.2.0 |
| coc.nvim | 0.0.78 |
| coc-markdownlint | 1.10.0 |

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release.

**Comment by weierophinney** [comment]
Thanks - updated to coc.nvim 0.0.80, and coc-markdownlint 1.10.1; all is now working.
