### ISSUE TITLE
Please Leave an Example of a Full Config

### ISSUE THREAD

**Issue by psygo** [fannheyward/coc-markdownlint#388]
I'm very confused as to how to fiddle around configs for this extension. I'm not an expert at CoC &mdash; as are most people &mdash;, so it isn't very intuitive how to set this up properly inside `coc-settings.json`, specially when it comes to customizing the rules. Adding a rich config to `README.md` would make this much easier for everybody.

For example, how do I deactivate, say the `line-length` rule? Something like this?

```json
{
  "languageserver": {
    "markdown": {
      "markdownlint.config": {
        "MD013": false
      },
      "filetypes": ["markdown"]
    },
}
```

(Probably not that, I know...)

**Comment by fannheyward** [comment]
```json
{
  "markdownlint.config": {
    "default": true,
    "line-length": false
  }
}
```

**Comment by psygo** [comment]
That doesn't seem to work. I get 2 warnings: one about missing `module` and `filetype` properties; and another about `markdownlint.config` not being allowed (both come from `coc-json` apparently).

And could you please post references for what properties are available in this `markdownlint.config`?

**Comment by fannheyward** [comment]
Put this into coc-settings.json directly, not under `languageserver` section.

**Comment by psygo** [comment]
Once that configuration is at the top-most level, autocomplete &mdash; which I think is coming from `coc-json` &mdash; does work for all the rules apparently, you just have to get the names from the warnings/errors right next to the `MD---` indices. So I guess that's problem solved, even though references would be nice, since, for example, I can deactivate indentation warnings, but I don't know how to change the preferred indentation length to my liking.
