### ISSUE TITLE
Markdownlint not working, no linting shown and no service run

### ISSUE THREAD

**Issue by robinchm** [fannheyward/coc-markdownlint#445]
I installed coc.nvim with coc-markdownlint via coc-marketplace, all latest versions. After that I opened an MD file (README.md) with vim. No linting information is shown. Also when I check the result of `:CocList services`, no LSP is running.

My `:CocInfo` output:
```txt
## versions

vim version: VIM - Vi IMproved 8.2 8022086
node version: v12.22.3
coc.nvim version: 0.0.80-3086844413
coc.nvim directory: /home/******/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-09-08T09:45:56.284 INFO (pid:260510) [plugin] - coc.nvim 0.0.80-3086844413 initialized with node: v12.22.3 after 62ms
2021-09-08T09:46:00.146 INFO (pid:260510) [attach] - receive notification: showInfo []
```

My `:CocConfig` is an empty json.
Am I missing some critical dependency or configuration? Other plugins like pyright and go work fine with their respective file types.

**Comment by fannheyward** [comment]
Yes, markdownlint isn't listed in `:CocList services`. Checkout `:CocList extensions`, do you have sign `*` before coc-markdownlint?

**Comment by robinchm** [comment]
![image](https://user-images.githubusercontent.com/22679145/132439373-2f121c4f-e389-4621-85eb-ec046840ede0.png)
Just checked there's no `*` before the plugin. I can switch it on by pressing enter over that entry, but still no linting.

**Comment by fannheyward** [comment]
Looks like it's not activated, do you open a markdown file ? What's the output of `:verbose set filetype?` and `:echo &filetype`?

**Comment by robinchm** [comment]
Oh indeed it's not markdown filetype. Turned out that plugin 'vimwiki' automatically sets all md file as vimwiki filetype. After I disable this behaviour the linting is working fine.

I'll need to figure out how to configure vimwiki's filetype setting, but that's another story.

Thanks a lot for your timely help!

**Comment by fannheyward** [comment]
Check `:h coc_filetype_map`, this will make current document to another filetype that used for coc.nvim.

**Comment by fannheyward** [comment]
For example, I use this to make asciidoc as markdown, but with `echo &ft` still asciidoc.

```viml
let g:coc_filetype_map = {
      \ 'asciidoc': 'markdown',
      \ }
```

**Comment by robinchm** [comment]
It's a vimwiki-specific issue. I'll leave the solution here just in case (very unlikely) someone runs into the same issue.

I don't know why but assigning a filetype using `au BufNewFile,BufRead *.md set filetype=markdown` when you have vimwiki does not work, somehow it manages to hijack all ".md" files and mark their filetype as "vimwiki". What I do is:
```vim
let g:vimwiki_ext2syntax = {}
```

This will tell vimwiki to only hijack those files with extension ".wiki", leaving markdown files untouched.
