### ISSUE TITLE
Questions from your screenshot

### ISSUE THREAD

**Issue by dngray** [fannheyward/coc-markdownlint#450]
![image](https://user-images.githubusercontent.com/345274/66532165-f0afd400-eb40-11e9-99a7-2b30fb03e258.gif)

1. What config did you do to get the ⚠️?
2. How did you get the highlighting on "https", is that neoclide/coc-prettier?

**Comment by fannheyward** [comment]
Sorry for the late response.

1. coc-markdownlint will lint the MD file, provides diagnostics to coc.nvim, coc will display the sign to signcolumn. By default, warning sign is ⚠️, you can change `diagnostic.warningSign` in your coc-settings.json.
2. the highlighting on url is came from nvim.
