### ISSUE TITLE
$ref '/properties/MD053' in 'vscode://settings' can not be resolved.

### ISSUE THREAD

**Issue by andys8** [fannheyward/coc-markdownlint#464]
Since a few weeks I started seeing this error message when opening `coc-settings.json`.

>  [json 768] [W] $ref '/properties/MD053' in 'vscode://settings' can not be resolved.

![image](https://user-images.githubusercontent.com/13085980/182358932-7f8353bd-f9a3-4065-a5f1-7b9e93f639ba.png)

I do not know if the issue is related to a change or issue in coc itself, in `coc-markdownlint` or (potentially) in my configuration. My assumption is that the error is related to `coc-markdownlint` because the message is complaining about `MD053`, but that's basically it. I don't know why a JSON file is relevant for markdownlint

Do you have any idea where that issue could be coming from and how to fix it?

## System

*  Manjaro Linux
* Vi IMproved 9.0
* CoC latest release branch
* https://github.com/andys8/dotfiles/blob/0929c5b5cf0d0bef29010e7f8ba5b0e59bb290c1/coc-settings.json
* https://github.com/andys8/dotfiles/blob/master/markdownlintrc

**Comment by fannheyward** [comment]
Released in v1.12.7
