### ISSUE TITLE
[question] No any warning dispayed in Windows 11 and PowerSehll 7.

### ISSUE THREAD

**Issue by SetsuikiHyoryu** [fannheyward/coc-markdownlint#495]
I tried write some wrong style, but no any warning displayed.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/57035251/214763066-08e9eff4-a8c4-4e2b-9feb-fc22067e712f.png">

This is my CocList, and coc-markdownlint is in this list:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/57035251/214763302-6264d474-ef28-4e79-985e-fdb0632f55ab.png">

And I tried `CocList commands` but it tell me No result for search markdownlint commands:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/57035251/214763674-fc66c7d6-6267-474f-8e68-c7f91e9ee53c.png">

My OS is windows 11, and using PowerShell 7.

**Comment by fannheyward** [comment]
Sorry I don't have a Win 11+PowerShell env to debug this. The document is checked by markdownlint and reports diagnostics to coc-markdownlint to display, maybe there's something broken with markdownlint on this env.

**Comment by SetsuikiHyoryu** [comment]
> Sorry I don't have a Win 11+PowerShell env to debug this. The document is checked by markdownlint and reports diagnostics to coc-markdownlint to display, maybe there's something broken with markdownlint on this env.

I used markdownlint in VSCode is no problem. Maybe it has some problem on powershell.

**Comment by fannheyward** [comment]
@SetsuikiHyoryu try https://github.com/DavidAnson/markdownlint-cli2 with PowerShell, does it work?

**Comment by fannheyward** [comment]
Any errors in `:CocCommand workspace.showOutput markdownlint`?

**Comment by SetsuikiHyoryu** [comment]
> Any errors in `:CocCommand workspace.showOutput markdownlint`?

<img width="533" alt="image" src="https://user-images.githubusercontent.com/57035251/215704001-78411c82-2f31-472f-9587-514fe7af4619.png">

No any messages.

**Comment by SetsuikiHyoryu** [comment]
> `:CocCommand workspace.showOutput markdownlint` should open a new buffer, displayed markdownlint configs:
> 
> <img alt="截屏2023-01-31 16 17 30" width="712" src="https://user-images.githubusercontent.com/345274/215704503-ea4509c8-8381-4e1a-b9ea-affe63cf3f21.png">

<img width="835" alt="image" src="https://user-images.githubusercontent.com/57035251/215706099-ede8c6be-aea2-4213-8c60-913b3fa8151d.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/57035251/215706151-61cde7dc-a62e-4185-9f13-7bdf32230ae5.png">

It looks like fail to create buffer.

**Comment by fannheyward** [comment]
`:CocCommand workspace.showOutput` ?

**Comment by SetsuikiHyoryu** [comment]
> `:CocCommand workspace.showOutput` ?

<img width="841" alt="image" src="https://user-images.githubusercontent.com/57035251/215706723-87be1b22-ec7b-48c2-906f-9f09d8ccb6ad.png">

Oh, something displayed.

**Comment by SetsuikiHyoryu** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/57035251/215707397-3caf667a-2d47-4e9a-aa86-867f7798b261.png">

It displayed prettier info where I choosed 2.

**Comment by fannheyward** [comment]
It's strange that no `markdownlint` displayed in the list. What's your `:CocInfo` and `:CocOpenLog`?

**Comment by SetsuikiHyoryu** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/57035251/215708411-1463479e-3769-4f2d-90f3-47382c93a59d.png">

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/57035251/215708491-8064d9cc-d77a-43d9-9348-6b4d87a3a032.png">

Looks like something wrong.

**Comment by fannheyward** [comment]
Upgrade your coc.nvim please. The `URL is not defined` error is caused by extension sandbox env, coc has fixed this in latest release.

**Comment by SetsuikiHyoryu** [comment]
> Upgrade your coc.nvim please. The `URL is not defined` error is caused by extension sandbox env, coc has fixed this in latest release.

Tankyou! I'm going to try it. If succeed, I will close this issue.

**Comment by SetsuikiHyoryu** [comment]
Thankyou! It works now.
